#!/usr/bin/env bash

set -euo pipefail

[[ $1 = run-example ]] && shift

example="${1}"

print_sep() {
  columns=$(tput cols)
  ((c=columns-1))
  printf "=\e[%sb\n" $c
}

print_sep


# Compile and run and unit tests
cargo rustc --example "${example}" -- --test
./target/debug/examples/"${example}"

# Run it too.
cargo run --example "${example}"
